minor bug fix
minor change to line 385 -- upon unsuccessful exit, program now replies: 
```
Error: Invalid argument.
Usage:

    shyaml (-h|--help)
    shyaml ACTION KEY [DEFAULT]
```

Previously: 
```
Traceback (most recent call last):
  File "/usr/local/bin/shyaml", line 389, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/shyaml", line 385, in main
    die("Invalid argument.\n%s" % usage)
NameError: global name 'usage' is not defined
```